retAddr: retAddr2.c
#	@echo "-g: GDB Debug flag enabled"
#	@echo "-z execstack: DEP disabled"
#	@echo "-fno-stack-protector: Stack smashing protection disabled"
#	@echo
	gcc-5 -g -z execstack -fno-stack-protector -o retAddr2 retAddr2.c
